# Generated by Django 2.1.4 on 2019-01-12 09:56

from django.conf import settings
from django.db import migrations, models
import git.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('upload', models.FileField(upload_to=git.models.user_directory_path)),
                ('usern', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
