# Generated by Django 2.1.4 on 2019-01-11 18:09

from django.db import migrations, models
import git.models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_auto_20190110_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='upload',
            field=models.FileField(default='aaa', upload_to=git.models.user_directory_path),
            preserve_default=False,
        ),
    ]
